config/routes.rb
Rails.application.routes.draw do
  # get 'watch_party/home'
  # get 'watch_party/login'
  # get 'watch_party/party'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'watch_party#home'
  get '/party', to: 'watch_party#party'
  post '/login', to: 'watch_party#login'
  get "/leave_call", to: "watch_party#leave_call"
  delete "end_call", to: "watch_party#end_call"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/watch_party.rb
class WatchParty < ApplicationRecord
    require 'opentok'
  
    @opentok = OpenTok::OpenTok.new ENV['OPENTOK_API_KEY'], ENV['OPENTOK_API_SECRET']
  
    def self.create_or_load_session_id
      if WatchParty.any?
        last_session = WatchParty.last
        if last_session && last_session.expired == false
          @session_id = last_session.session_id
          @session_id
        elsif (last_session && last_session.expired == true) || !last_session
          @session_id = create_new_session
        else
          raise 'Something went wrong with the session creation!'
        end
      else
        @session_id = create_new_session
      end
    end
  
    def self.create_new_session
      session = @opentok.create_session
			record = WatchParty.new
			record.session_id = session.session_id
			record.save
			@session_id = session.session_id
			@session_id
    end
  
    def self.create_token(user_name, moderator_name, session_id)
      @token = user_name == moderator_name ? @opentok.generate_token(session_id, { role: :moderator }) : @opentok.generate_token(session_id)
    end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/watch_party_controller.rb
class WatchPartyController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_opentok_vars, only: :party

  def home
  end

  def login
    @name = login_params[:name]
    if login_params[:password] == ENV['PARTY_PASSWORD']
      @session_id = WatchParty.create_or_load_session_id
      redirect_to party_path(name: @name)
    else
      redirect_to('/', flash: { error: 'Incorrect password' })
    end

  end

  def party
    
  end

  def leave_call
    session = WatchParty.last
    session.expired = true
    session.save
    redirect_to root_path
  end

  def end_call
    sessions = WatchParty.last
    sessions.destroy
    redirect_to root_path
  end

  private

  def set_opentok_vars
    @api_key = ENV['OPENTOK_API_KEY']
    @api_secret = ENV['OPENTOK_API_SECRET']
    @session_id = WatchParty.find_by(expired: false).session_id
    @moderator_name = ENV['MODERATOR_NAME']
    @name ||= params[:name]
    @token = WatchParty.create_token(@name, @moderator_name, @session_id)
  end

  def login_params
    params.permit(:name, :password, :authenticity_token, :commit)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/watch_party_helper.rb
module WatchPartyHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoExpress</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags%>
    <script src="https://static.opentok.com/v1/js/video-express.js"></script>
    <%# <link rel="stylesheet" href="/video-express-styles.css" media="screen" charset="utf-8"> %>


  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/watch_party/home.html.erb
<div class="card-wrapper">
  <vwc-card>
    <div slot="main" id="box">
      <vwc-text font-face="subtitle-1" >Big Game Watch Party
        <br>
        <span><vwc-text font-face="body-1-code">Built With Vonage Video Express on Rails</vwc-text></span></vwc-text>
        <main>
        <div class="landing">
            <h1><%= @welcome_message %></h1>
            <p><%= @name_form_text %></p>
            <%= form_with(url: "/login", method: "post") do %>
            <%= text_field_tag 'name', nil, :placeholder => @name_placeholder_text %>
            <%= password_field_tag 'password', nil, :placeholder => @password_placeholder_text %>
            <%= submit_tag @name_form_submit_button_text %>
            <% flash.each do |type, msg| %>
                <p class="error"><%= msg %></p>
            <% end %>
            <% end %>
        </div>
        </main>
    </div>
  </vwc-card>
</div>

app/views/watch_party/party.html.erb
<%# <script src="https://static.opentok.com/v1/js/video-express.js"></script> %>
<script src="https://static.opentok.com/v2/js/opentok.min.js"></script>
<header>
  <!-- Header Will Go Here -->
  <%= render partial: 'components/header' %>
 <div id="screen" class="screen"></div>

  <!-- These are both new too -->


</header>
<main>
  <!-- This element is new -->


<main class="app">
  <div id="roomContainer"></div>
  <menu>
    <!-- Toolbar Will Go Here -->
     <%= render partial: 'components/toolbox' %>
     <%= link_to "Leave Meeting", leave_call_path %>
     <% if @name == @moderator_name %>
      <%= button_to "End Call", end_call_path, method: :delete, onclick: "location.reload() " %>
     <% end %>
     <%#debugger%>
     <%#session = OpenTok.initSession(@apiKey, session_id)%>
     <button onclick=session.forceMuteAll();>Mute all </button>
  </menu>

    <div id="screen" class="screen"></div>

  <!-- These two elements already exist from the first tutorial -->
  <div id="subscriber" class="subscriber"></div>
  <div id="publisher" class="publisher"></div>

  <!-- These are both new too -->
  <button id="startScreenShare" class="screen-share">Share Screen</button>
  <button id="stopScreenShare" class="screen-share hidden">Stop Sharing Screen</button>

</main>
</main>




<script>
  const room = new VideoExpress.Room({
   apiKey: '<%= @api_key %>', // add your OpenTok API key
   sessionId: '<%= @session_id %>', // add your OpenTok Session ID
   token: '<%= @token %>', // add your OpenTok token
   roomContainer: 'roomContainer',
   participantName: '<%= @name %>'
 
 });
 room.join();



 window.onMuteAudioButton = function(room){
  room.localParticipant.audioTracks.forEach(function(audioTrack) {
     audioTrack.track.disable();
  });
   $("#call-mute-btn").addClass("d-none");
   $("#call-unmute-btn").removeClass("d-none");
};

window.onUnMuteAudioButton = function(room){
     room.localParticipant.audioTracks.forEach(function(audioTrack) {
     audioTrack.track.enable();
   });
  $("#call-mute-btn").removeClass("d-none");
  $("#call-unmute-btn").addClass("d-none");
};


</script>

  <script>
    let session;
    fetch(location.pathname, { method: "get" })
      .then(res => {
        return res.json();
      })
      .then(res => {
        const apiKey = res.apiKey;
        const sessionId = res.sessionId;
        const token = res.token;
        initializeSession(apiKey, sessionId, token);
      })
      .catch(handleCallback);
    function initializeSession(apiKey, sessionId, token) {
      // Create a session object with the sessionId
      session = OT.initSession(apiKey, sessionId);
      // Create a publisher
      const publisher = OT.initPublisher(
        "publisher",
        {
          insertMode: "append",
          width: "300px",
          height: "300px"
        },
        handleCallback
      );
      // Connect to the session
      session.connect(token, error => {
        // If the connection is successful, initialize the publisher and publish to the session
        if (error) {
          handleCallback(error);
        } else {
          session.publish(publisher, handleCallback);
        }
      });
      // Subscribe to a newly created stream
      session.on("streamCreated", event => {
        const streamContainer =
          event.stream.videoType === "screen" ? "screen" : "subscriber";
        session.subscribe(
          event.stream,
          streamContainer,
          {
            insertMode: "append",
            width: "300px",
            height: "300px"
          },
          handleScreenShare(event.stream.videoType)
        );
      });
      session.on("streamDestroyed", event => {
        document.getElementById("screen").classList.remove("sub-active");
      });
    }
    // Function to handle screenshare layout
    function handleScreenShare(streamType, error) {
      if (error) {
        console.log("error: " + error.message);
      } else {
        if (streamType === "screen") {
          document.getElementById("screen").classList.add("sub-active");
        }
      }
    }
    // Callback handler
    function handleCallback(error) {
      if (error) {
        console.log("error: " + error.message);
      } else {
        console.log("callback success");
      }
    }
    let screenSharePublisher;
    const startShareBtn = document.getElementById("startScreenShare");
    startShareBtn.addEventListener("click", event => {
      OT.checkScreenSharingCapability(response => {
        if (!response.supported || response.extensionRegistered === false) {
          alert("Screen sharing not supported");
        } else if (response.extensionInstalled === false) {
          alert("Browser requires extension");
        } else {
          screenSharePublisher = OT.initPublisher(
            "screen",
            {
              insertMode: "append",
              width: "300px",
              height: "300px",
              videoSource: "screen",
              publishAudio: true
            },
            handleCallback
          );
          session.publish(screenSharePublisher, handleCallback);
          startShareBtn.classList.toggle("hidden");
          stopShareBtn.classList.toggle("hidden");
          document.getElementById("screen").classList.add("pub-active");
        }
      });
    });
    const stopShareBtn = document.getElementById("stopScreenShare");
    stopShareBtn.addEventListener("click", event => {
      screenSharePublisher.destroy();
      startShareBtn.classList.toggle("hidden");
      stopShareBtn.classList.toggle("hidden");
      document.getElementById("screen").classList.remove("pub-active");
    });

  </script>